name: Deploy Resources via Terraform

on:
  workflow_dispatch:
    inputs:
      num-instances:
        description: "Number of virtual machines and associated resources to deploy"
        type: number
        default: 3

env:
  TF_VAR_INPUT_NUM_INSTANCES: ${{ github.event.inputs.num-instances }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      # Download repo files
      - uses: actions/checkout@v4
      # Terraform setup steps
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -out tfplan
      # Do it for real
      - run: terraform apply tfplan
