name: Deploy Resources via Terraform

on:
  push:
  workflow_dispatch:

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    steps:
      # Download repo files
      - uses: actions/checkout@v4
      # Terraform setup steps
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate
      - run: terraform plan
      # Do it for real
      - run: terraform apply
