name: Deploy Resources via Terraform

on:
  push:
  workflow_dispatch:

env:
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      # Download repo files
      - uses: actions/checkout@v4
      # Terraform setup steps
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -out
      # Do it for real
      - run: terraform apply
