name: Destroy all deployed resources via Terraform

on:
  workflow_dispatch:
    inputs:
      num-instances:
        description: "Number of virtual machines and associated resources to DESTROY"
        type: number
        default: 3

env:
  # Case sensitive on unix
  TF_VAR_num_instances: ${{ github.event.inputs.num-instances }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

jobs:
  terraform-deploy:
    defaults:
      run:
        working-directory: ./terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform destroy -auto-approve
